import { PokemonProvider } from "@/context/PokemonContext";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Pokemon app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PokemonProvider>
        <body>{children}</body>
      </PokemonProvider>
    </html>
  );
}
